- name: Create new project for quarkus-droneshop
  command: "{{ oc_location }}  new-project {{ project_namespace }}"
  register: create_project_result
  when: not delete_deployment|bool

- name: Switch to project for  quarkus-droneshop
  command:  "{{ oc_location }}  project {{ project_namespace }}"
  when: not delete_deployment|bool