# From repository
- name: Add quarkusdroneshop helm chart repo
  kubernetes.core.helm_repository:
    name: quarkusdroneshop-helm
    repo_url: "https://quarkusdroneshop.github.io.quarkusdroneshop-helm/"
  when: not delete_deployment|bool
  tags: helm

- name: retrieve database password
# Newer version of Ansible call this module k8s_info
  kubernetes.core.k8s_info:
    api: v1
    kind: Secret
    name: droneshopdb-pguser-droneshopadmin
    namespace: "{{ project_namespace }}"
  register: databasepassword
  when: not delete_deployment|bool
  tags:
    - helm

- name: Get the original cred secrets
  set_fact:
    original_secret: "{{ item.data.password }}"
  with_items: "{{ databasepassword.resources }}"
  when: not delete_deployment|bool
  no_log: true
  tags:
    - helm

- name: Get postgres password
  set_fact:
    postgres_password: '{{ original_secret| b64decode }}'
  when: not delete_deployment|bool
  tags: 
    - helm

- name: Copying over  quarkusdroneshop helm chart values
  template:
    src: templates/vaules.yaml.j2
    dest:  "{{ config_location }}/vaules.yaml"
    owner: "{{ default_owner }}"
    group: "{{ default_group }}"
    mode: 0666
  tags: helm

- name: Copying over quarkusdroneshop-web route
  template:
    src: templates/docker/quarkusdroneshop-web.yaml.j2
    dest:  "{{ config_location }}/quarkusdroneshop-web.yaml"
    owner: "{{ default_owner }}"
    group: "{{ default_group }}"
    mode: 0666
  tags: helm

- name: Deploy quarkusdroneshop helm chart to project
  kubernetes.core.helm:
    name: quarkusdroneshop-helm
    chart_ref: quarkusdroneshop-helm/quarkusdroneshop-charts
    chart_version: "{{ helm_chart_version }}"
    release_namespace: "{{ project_namespace }}"
    update_repo_cache: true 
    values_files:
      -  "{{ config_location }}/vaules.yaml"
  when: not delete_deployment|bool
  tags: helm

- name:  Create quarkusdroneshop-web route 
  command: "{{ oc_location }}  create -f {{ config_location }}quarkusdroneshop-web.yaml"
  when: not delete_deployment|bool
  tags: helm

- name: Remove test release and waiting suppression ending
  kubernetes.core.helm:
    name: quarkusdroneshop-helm
    state: absent
    release_namespace: "{{ project_namespace }}"
    wait: true
  when:  delete_deployment|bool
  tags: helm

- name:  Delete quarkusdroneshop-web route 
  command: "{{ oc_location }}  delete -f {{ config_location }}quarkusdroneshop-web.yaml"
  when:  delete_deployment|bool
  tags: helm