apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cafe-cluster-kafka
  namespace: quarkusdroneshop-demo
spec:
  serviceName: "cafe-cluster-kafka"
  replicas: 3
  selector:
    matchLabels:
      strimzi.io/cluster: cafe-cluster
  template:
    metadata:
      labels:
        strimzi.io/cluster: cafe-cluster
    spec:
      initContainers:
        - name: init-config
          command:
            - sh
            - -c
            - |
              echo "listeners=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9091" > /tmp/strimzi.properties
              echo "advertised.listeners=PLAINTEXT://external-cafe-cluster-kafka-asite:9094" >> /tmp/strimzi.properties
          volumeMounts:
            - name: config-volume
              mountPath: /opt/kafka/config
      containers:
        - name: kafka
          image: strimzi/kafka:latest
          volumeMounts:
            - name: config-volume
              mountPath: /opt/kafka/config
      volumes:
        - name: config-volume
          emptyDir: {}