apiVersion: v1
kind: ConfigMap
metadata:
  name: droneshop-sub-config
  namespace: quarkusdroneshop-demo
data:
  KAFKA_BOOTSTRAP_URLS: "shop-cluster-kafka-bootstrap:9092"
  QUARKUS_LOG_LEVEL: "INFO"
  QUARKUSDRONESHOP_LOG_LEVEL: "INFO"
  REST_URL: "http://localhost:8080/order"