apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: quarkusdroneshop-rhdh
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  app-config-rhdh.yaml: |
    app:
      title: Red Hat Developer Hub
      baseUrl: ${BASE_URL}
    backend:
      auth:
        externalAccess:
        - type: legacy
          options:
            secret: "${BACKEND_SECRET}"
            subject: legacy-default-config
      baseUrl: ${BASE_URL}
      cors:
        origin: ${BASE_URL}
    auth:
      environment: production
      providers:
        github:
          production:
            clientId: ${AUTH_GITHUB_CLIENT_ID}
            clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
            signIn:
              resolver:
                type: email
                options:
                  emailMatchingUserEntityAnnotation: backstage.io/email
                  dangerouslyAllowSignInWithoutUserInCatalog: true
    integrations:
      github:
        - host: ${GITHUB_HOST_DOMAIN}
          apps:
            - appId: ${AUTH_GITHUB_APP_ID}
              clientId: ${AUTH_GITHUB_CLIENT_ID}
              clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
              webhookUrl: ${GITHUB_WEBHOOK_URL}
              webhookSecret: ${GITHUB_WEBHOOK_SECRET}
              privateKey: |
                ${GITHUB_PRIVATE_KEY_FILE}
    signInPage: github
    catalog:
      providers:
        githubOrg:
          githubUrl: https://${GITHUB_HOST_DOMAIN}
          orgs:
            - ${GITHUB_ORGANIZATION}
          token: ${GITHUB_TOKEN}
          schedule:
            frequency: PT60S
            initialDelay: PT30S
            timeout: PT120S
      locations:
        - type: file
          target: /opt/app-root/src/catalog-info.yaml
          rules:
            - allow:
                - User
        - type: url
          target: https://github.com/nmushino/quarkusdroneshop-ansible/blob/master/openshift/counter-development.yaml
          rules:
            allow:
              - Component
              - Template
              - User
    featureFlags:
      scaffolder: true