apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: buildah
spec:
  steps:
  - name: build
    securityContext:
      privileged: true
      runAsUser: 0
      runAsGroup: 0
    image: quay.io/buildah/stable
    script: |
      #!/bin/sh
      buildah bud --format docker -t $(params.IMAGE) -f $(params.DOCKERFILE) $(params.CONTEXT)
  params:
    - name: IMAGE
      type: string
    - name: DOCKERFILE
      type: string
    - name: CONTEXT
      type: string
  workspaces:
    - name: source