apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: counter
  description: Counter microservice
  annotations:
    backstage.io/kubernetes-label-selector: 'app=counter'
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: user:default/nmushino