apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: counter
  description: Counter app for quarkusdroneshop
  annotations:
    backstage.io/kubernetes-id: counter
spec:
  type: service
  lifecycle: production
  owner: user:default/nmushino