apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: nmushino
  annotations:
    backstage.io/email: nmushino@redhat.com
spec:
  profile:
    displayName: Noriaki Mushino
    email: nmushino@redhat.com
  memberOf: []