apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: nmushino  # ← GitHub の username（ログイン中の人）
spec:
  profile:
    displayName: Noriaki Mushino
    email: nmushino@example.com
  memberOf: []