apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-info
  namespace: quarkusdroneshop-rhdh
data:
  catalog-info.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: nmushino
      annotations:
        backstage.io/email: nmushino@redhat.com
    spec:
      profile:
        displayName: Noriaki Mushino
        email: nmushino@redhat.com
      memberOf: []

    ---
    apiVersion: backstage.io/v1alpha1
    kind: Template
    metadata:
      name: sample-template
      title: Sample Template
      description: Create メニュー動作確認用テンプレート
      tags:
        - recommended
    spec:
      owner: user:default/nmushino
      type: service
      parameters:
        - title: Service Name
          required:
            - name
          properties:
            name:
              type: string
              title: Name
      steps:
        - id: log-message
          name: Log message
          action: debug:log
          input:
            message: "Scaffolder executed for ${{ parameters.name }}"
    enabled:
      kubernetes: true
    kubernetes:
      clusterLocatorMethods:
      - clusters:
        - authProvider: serviceAccount
          name: ${K8S_CLUSTER_NAME}
          serviceAccountToken: ${K8S_CLUSTER_TOKEN}
          url: ${K8S_CLUSTER_URL}
          skipTLSVerify: true
        type: config
      customResources:
      - apiVersion: v1
        group: route.openshift.io
        plural: routes
      serviceLocatorMethod:
        type: singleTenant