apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeoffice-backend
  namespace: quarkusdroneshop-demo
  labels:
    app: homeoffice-backend
    environment: production
    category: droneshop
spec:
  template:
    spec:
      containers:
      - name: homeoffice-backend
        env:
           - name: POSTGRESQL_JDBC_URL
             valueFrom:
               configMapKeyRef:
                 name: droneshop-config
                 key: PGSQL_URL
           - name: POSTGRESQL_USER
             valueFrom:
               secretKeyRef:
                 name: droneshopdb-pguser-droneshopadmin
                 key: user
           - name: POSTGRESQL_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: droneshopdb-pguser-droneshopadmin
                 key: password