apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: quarkusdroneshop-demo
  labels:
    app: inventory
    environment: production
    category: droneshop
spec:
  template:
    spec:
      containers:
       - name: inventory
         env:
           - name: PGSQL_URL
             valueFrom:
               configMapKeyRef:
                 name: droneshop-config
                 key: PGSQL_URL
           - name: PGSQL_USER
             valueFrom:
               secretKeyRef:
                 name: droneshopdb-pguser-droneshopadmin
                 key: user
           - name: PGSQL_PASS
             valueFrom:
               secretKeyRef:
                 name: droneshopdb-pguser-droneshopadmin
                 key: password
           - name: KAFKA_BOOTSTRAP_URLS
             valueFrom:
               configMapKeyRef:
                 name: droneshop-config
                 key: KAFKA_BOOTSTRAP_URLS