apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: openshift-client
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"Task","metadata":{"annotations":{"tekton.dev/categories":"Openshift","tekton.dev/displayName":"openshift client","tekton.dev/pipelines.minVersion":"0.17.0","tekton.dev/platforms":"linux/amd64","tekton.dev/tags":"cli"},"labels":{"app.kubernetes.io/version":"0.2"},"name":"openshift-client","namespace":"quarkusdroneshop-cicd"},"spec":{"description":"This task runs commands against the cluster provided by user and if not provided then where the Task is being executed.\nOpenShift is a Kubernetes distribution from Red Hat which provides oc, the OpenShift CLI that complements kubectl for simplifying deployment and configuration applications on OpenShift.","params":[{"default":"oc help","description":"The OpenShift CLI arguments to run","name":"SCRIPT","type":"string"},{"default":"4.7","description":"The OpenShift Version to use","name":"VERSION","type":"string"}],"steps":[{"image":"quay.io/openshift/origin-cli:$(params.VERSION)","name":"oc","script":"#!/usr/bin/env bash\n\n[[ \"$(workspaces.manifest-dir.bound)\" == \"true\" ]] \u0026\u0026 \\\ncd $(workspaces.manifest-dir.path)\n\n[[ \"$(workspaces.kubeconfig-dir.bound)\" == \"true\" ]] \u0026\u0026 \\\n[[ -f $(workspaces.kubeconfig-dir.path)/kubeconfig ]] \u0026\u0026 \\\nexport KUBECONFIG=$(workspaces.kubeconfig-dir.path)/kubeconfig\n\n$(params.SCRIPT)\n"}],"workspaces":[{"description":"The workspace which contains kubernetes manifests which we want to apply on the cluster.","name":"manifest-dir","optional":true},{"description":"The workspace which contains the the kubeconfig file if in case we want to run the oc command on another cluster.","name":"kubeconfig-dir","optional":true}]}}
    tekton.dev/categories: Openshift
    tekton.dev/displayName: openshift client
    tekton.dev/pipelines.minVersion: 0.17.0
    tekton.dev/platforms: linux/amd64
    tekton.dev/tags: cli
  generation: 1
  labels:
    app.kubernetes.io/version: "0.2"
  namespace: quarkusdroneshop-cicd
spec:
  description: |-
    This task runs commands against the cluster provided by user and if not provided then where the Task is being executed.
    OpenShift is a Kubernetes distribution from Red Hat which provides oc, the OpenShift CLI that complements kubectl for simplifying deployment and configuration applications on OpenShift.
  steps:
    - name: oc-command
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/bin/sh
        set -x
        echo "Running OpenShift Client Task"
        echo "Current User: $(oc whoami)"
        echo "Current Namespace: $(oc project -q)"
        echo "OC Version: $(oc version)"
        echo "Executing User Provided Script: $(params.SCRIPT)"
        $(params.SCRIPT)
  params:
    - name: SCRIPT
      description: "The OpenShift CLI script to run"
      type: string
      default: "oc version"
  workspaces:
  - description: The workspace which contains kubernetes manifests which we want to
      apply on the cluster.
    name: manifest-dir
    optional: true
  - description: The workspace which contains the the kubeconfig file if in case we
      want to run the oc command on another cluster.
    name: kubeconfig-dir
    optional: true
