apiVersion: apps/v1
kind: Deployment
metadata:
  name: QDCA10
  namespace: quarkusdroneshop-demo
  labels:
    app: QDCA10
    environment: production
    category: droneshop
spec:
  template:
    spec:
      containers:
       - name: QDCA10
         env:
           - name: KAFKA_BOOTSTRAP_URLS
             valueFrom:
               configMapKeyRef:
                 name: droneshop-config
                 key: KAFKA_BOOTSTRAP_URLS